from datetime import datetime

def create_file_summary(file_name: str, summary_content: str) -> str:
    """
    Write a structured summary for a data file to /memory/{file_name}.md.
    
    This tool creates a standardized summary file with:
    - Clear header indicating this is a summary, not the original file
    - Timestamp of when the summary was created
    - The file name being summarized
    - The summary content provided
    
    Use this after calling preview_data_file() to document what's in the file.
    
    Args:
        file_name: Name of the file being summarized (e.g., "data.xlsx" or "triangles.csv")
        summary_content: The summary text describing the file structure, columns, data characteristics, and purpose
    
    Returns:
        Confirmation message with the path where the summary was written.
    
    Example:
        write_file_summary(
            file_name="claims_data.xlsx",
            summary_content="Excel file with 3 sheets (HMO, PPO, POS). Contains loss triangles with columns for accident year and development periods. Used for reserve analysis."
        )
    """
    
    # Get current timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Create structured summary content
    structured_content = f"""# FILE SUMMARY

**This is a summary document, not the original data file.**

## File Information
- **File Name:** {file_name}
- **Summary Created:** {timestamp}
- **Location:** /agent-files/{file_name}

## Summary

{summary_content}

---
*This summary was automatically generated by TeamAnalyst to provide quick reference without opening the full data file.*
"""
    
    # Write the summary
    return structured_content
